# sudo docker build -f Dockerfile.txt -t tengine . 
FROM nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04
RUN apt-get update && apt-get install -y git libgtk2.0-dev \
    libgtk-3-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev python-dev python-numpy \
    libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libdc1394-22-dev wget zip unzip  gdb vim
RUN  apt-get install -y software-properties-common && add-apt-repository ppa:deadsnakes/ppa && apt update &&\
    apt install -y python3.7 python3-pip
RUN mkdir ~/.pip && echo "[global]\ntimeout = 60\nindex-url = https://pypi.doubanio.com/simple" > ~/.pip/pip.conf
RUN python3.7 -m pip install  -U pip && python3.7 -m pip install cmake

WORKDIR /
# RUN wget https://github.com/opencv/opencv/archive/4.5.1.zip 
RUN git clone --depth 1 --branch 4.5.1 https://gitee.com/lyyiangang/opencv.git
# build opencv for x86
RUN cd opencv && mkdir build && cd build && cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D WITH_TBB=ON \
    -DCMAKE_INSTALL_PREFIX=/install_x86 \
    -D WITH_V4L=ON  -DBUILD_TIFF=ON -DWITH_GTK_2_X=ON .. && \
    make -j3 install
RUN apt-get install -y libprotobuf-dev protobuf-compiler